# Generated by Django 4.0.1 on 2022-09-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fpass_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
