# Generated by Django 4.0.1 on 2022-09-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_user_fpass_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='t_shirt_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
