# Generated by Django 4.0.1 on 2022-09-16 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_user_t_shirt_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('t_shirt_size', models.CharField(blank=True, max_length=5, null=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('team_name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=150)),
                ('catagory', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('distric', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('leader', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
