# Generated by Django 4.0.1 on 2022-09-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_team_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('video_url', models.URLField()),
                ('rodemap_banner', models.ImageField(upload_to='media/rodemap')),
                ('prize_logo', models.ImageField(upload_to='media/prize_logo')),
                ('foter_description', models.TextField(max_length=1000)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linked_in_link', models.URLField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, max_length=200, null=True)),
                ('phone1', models.CharField(blank=True, max_length=15, null=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('phone3', models.CharField(blank=True, max_length=15, null=True)),
                ('hotline1', models.CharField(blank=True, max_length=15, null=True)),
                ('hotline2', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
