# Generated by Django 4.0.1 on 2022-09-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='signature',
            field=models.BooleanField(default=True),
        ),
    ]
