# Generated by Django 4.0.1 on 2022-09-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_home_email_home_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='signature',
            field=models.CharField(default='roy77', max_length=5),
        ),
    ]
