# Generated by Django 4.0.1 on 2022-09-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_home_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_date', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=2)),
                ('month', models.CharField(max_length=5)),
                ('tag', models.CharField(max_length=20)),
                ('notice', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
