# Generated by Django 4.0.1 on 2022-09-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('s_description', models.TextField(max_length=150)),
                ('first_prize', models.CharField(blank=True, max_length=100, null=True)),
                ('secound_prize', models.CharField(blank=True, max_length=100, null=True)),
                ('third_prize', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
