# Generated by Django 4.0.1 on 2022-09-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_what_you_get'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=300)),
                ('s_about', models.TextField(max_length=200)),
                ('about', models.TextField(max_length=500)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
