# Generated by Django 4.0.1 on 2022-09-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_alter_news_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/sponsor')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
