# Generated by Django 4.0.1 on 2022-09-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_team_registration_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='upcomming_event',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='upcomming_event_venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
