# Generated by Django 4.0.1 on 2022-09-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_user_is_payment_done_user_is_team_registration_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_payment_apcepted',
            field=models.BooleanField(default=False),
        ),
    ]
