# Generated by Django 4.0.1 on 2022-09-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/catagory'),
        ),
    ]
